input_text = """
<div style="background-color:#ffffff;border-color:#eee;border-radius:15px;border-style:solid;border-width:1px;margin:0px 0px 0px 0px;padding:17px 17px 17px 17px;"><div style="padding-bottom:0px;padding-left:0px;padding-right:0px;padding-top:6px;"><h5 style="color:#ff4b6c;color:var(--wt-text-on-background-color) !important;font-family:'Helvetica',Arial,sans-serif;font-size:16px;font-weight:Bold;line-height:24px;margin:0;text-align:left;"><span style="">ALTCOINS</span></h5></div><div style="padding-bottom:5px;padding-left:0px;padding-right:0px;padding-top:5px;"><h1 style="color:#000000;color:var(--wt-text-on-background-color) !important;font-family:'Helvetica',Arial,sans-serif;font-size:27px;font-weight:Bold;line-height:41px;margin:0;text-align:left;"><span style="">Blockchain casinos just hit jackpot </span>🎰</h1></div><div style="padding-bottom:12px;padding-left:0px;padding-right:0px;padding-top:12px;"><img alt="" style="margin:0 auto 0 auto;width:100%;" src="https://media.beehiiv.com/cdn-cgi/image/fit=scale-down,format=auto,onerror=redirect,quality=80/uploads/asset/file/6b8a25ed-53a0-406d-a6fb-d108ebcbb2ae/image.png"><div style="margin:0 auto 0 auto;padding-left:0px;padding-right:0px;padding-top:0px;text-align:right;width:100%;"><small style="color:#999999;color:var(--wt-text-on-background-color) !important;font-family:'Helvetica',Arial,sans-serif;font-size:12px;font-style:normal;text-decoration-color:#999999;text-decoration:none;"><p><span style="">Analytics Insight</span></p></small></div></div><style>
  p span[style*="font-size"] { line-height: 1.6; }
</style><div style="padding-bottom:18px;padding-left:0px;padding-right:0px;padding-top:6px;"><p style="color:#222222;color:var(--wt-text-on-background-color) !important;font-family:'Helvetica',Arial,sans-serif;font-size:17px;line-height:26px;text-align:left;"><span style="">Ever feel like traditional casinos are a bit, you know, last century? </span><span style=""><a class="link" href="https://flight.beehiiv.net/v2/clicks/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1cmwiOiJodHRwczovL3d3dy5jb2luZ2Vja28uY29tL2VuL2NhdGVnb3JpZXMvZ2FtYmxpbmc_dXRtX3NvdXJjZT13d3cuY3J5cGRvbnV0cy5uZXdzJnV0bV9tZWRpdW09cmVmZXJyYWwmdXRtX2NhbXBhaWduPWJsb2NrY2hhaW4tY2FzaW5vcy1qdXN0LWhpdC1qYWNrcG90IiwicG9zdF9pZCI6IjE0NzZkYzc2LTRiNTgtNGNjMi05MjlhLTNjMGM1MTBiNjI3OSIsInB1YmxpY2F0aW9uX2lkIjoiYjMwZTUxN2UtZWM2MS00YzUwLWExZDYtYmRlNzA5YTFjMjUyIiwidmlzaXRfdG9rZW4iOiI4MmVjM2EzZS03YTBlLTQ5MzYtOWIyNy1mNGEwYjZlNzJiYzIiLCJpYXQiOjE2OTIxNTEwMjcuMzQ4LCJpc3MiOiJvcmNoaWQifQ.S7CeIJ7Bzul4ucZv5y-KjOf2hMGqQf-7nPF4lmpHnjQ" target="_blank" rel="noopener noreferrer nofollow" style="color:#2346ea;text-decoration:underline #2346ea;">Blockchain casinos</a></span><span style=""> are the new shiny thing, and they're as decentralized as a chaotic family reunion.</span></p></div><style>
  p span[style*="font-size"] { line-height: 1.6; }
</style><div style="padding-bottom:18px;padding-left:0px;padding-right:0px;padding-top:6px;"><p style="color:#222222;color:var(--wt-text-on-background-color) !important;font-family:'Helvetica',Arial,sans-serif;font-size:17px;line-height:26px;text-align:left;"><span style="">Here's a scoop on 2 casino projects that are the talk of the town:</span></p></div><div style="padding-bottom:0px;padding-left:0px;padding-right:0px;padding-top:18px;"><h3 style="color:#000000;color:var(--wt-text-on-background-color) !important;font-family:'Helvetica',Arial,sans-serif;font-size:22px;font-weight:Bold;line-height:26px;margin:0;text-align:left;"><span style="">1/ Rollbit</span><span style=""><b>&nbsp;</b></span></h3></div><div style="padding-bottom:18px;padding-left:18px;padding-right:18px;padding-top:0px;"><ul style="color:var(--wt-text-on-background-color) !important;font-family:'Helvetica',Arial,sans-serif;font-size:18px;line-height:27px;list-style-type:disc;margin:0px 0px 0px 25px;padding:0;"><li style="margin:9px 0px 0px 0px;"><p style="text-align:left;"><span style=""><a class="link" href="https://flight.beehiiv.net/v2/clicks/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1cmwiOiJodHRwczovL3JvbGxiaXQuY29tP3V0bV9zb3VyY2U9d3d3LmNyeXBkb251dHMubmV3cyZ1dG1fbWVkaXVtPXJlZmVycmFsJnV0bV9jYW1wYWlnbj1ibG9ja2NoYWluLWNhc2lub3MtanVzdC1oaXQtamFja3BvdCIsInBvc3RfaWQiOiIxNDc2ZGM3Ni00YjU4LTRjYzItOTI5YS0zYzBjNTEwYjYyNzkiLCJwdWJsaWNhdGlvbl9pZCI6ImIzMGU1MTdlLWVjNjEtNGM1MC1hMWQ2LWJkZTcwOWExYzI1MiIsInZpc2l0X3Rva2VuIjoiODJlYzNhM2UtN2EwZS00OTM2LTliMjctZjRhMGI2ZTcyYmMyIiwiaWF0IjoxNjkyMTUxMDI3LjM0OCwiaXNzIjoib3JjaGlkIn0.dbHAseIrRP5AMsdpE0E9qrJ94BwKuYayZbrwIb7wE48" target="_blank" rel="noopener noreferrer nofollow" style="color:#2346ea;text-decoration:underline #2346ea;"><b>Market cap leader</b></a></span><span style=""> in casino category </span></p></li><li style="margin:9px 0px 0px 0px;"><p style="text-align:left;"><span style="">+80.9% past week</span></p></li><li style="margin:9px 0px 0px 0px;"><p style="text-align:left;"><span style="">They’ve got everything from roulettes to sports betting</span></p></li><li style="margin:9px 0px 0px 0px;"><p style="text-align:left;"><span style="">Actively buys back its utility token — $RLB with revenue</span></p></li><li style="margin:9px 0px 0px 0px;"><p style="text-align:left;"><span style="">24H Casino Revenue: </span><span style=""><b>$1,031,754</b></span></p></li></ul></div><style>
  p span[style*="font-size"] { line-height: 1.6; }
</style><div style="padding-bottom:18px;padding-left:0px;padding-right:0px;padding-top:6px;"><p style="color:#222222;color:var(--wt-text-on-background-color) !important;font-family:'Helvetica',Arial,sans-serif;font-size:17px;line-height:26px;text-align:left;"><span style=""><b>However, </b></span><span style="">they still have a centralized structure, which is a bit like hosting a punk rock concert in a library. It doesn’t quite solve all the problems blockchain is supposed to fix.</span></p></div><div style="padding-bottom:0px;padding-left:0px;padding-right:0px;padding-top:18px;"><h3 style="color:#000000;color:var(--wt-text-on-background-color) !important;font-family:'Helvetica',Arial,sans-serif;font-size:22px;font-weight:Bold;line-height:26px;margin:0;text-align:left;"><span style="">2/ WINR Protocol</span></h3></div><div style="padding-bottom:18px;padding-left:18px;padding-right:18px;padding-top:0px;"><ul style="color:var(--wt-text-on-background-color) !important;font-family:'Helvetica',Arial,sans-serif;font-size:18px;line-height:27px;list-style-type:disc;margin:0px 0px 0px 25px;padding:0;"><li style="margin:9px 0px 0px 0px;"><p style="text-align:left;"><span style=""><b>7-day </b></span><span style=""><a class="link" href="https://flight.beehiiv.net/v2/clicks/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1cmwiOiJodHRwczovL3dpbnIuZ2FtZXM_dXRtX3NvdXJjZT13d3cuY3J5cGRvbnV0cy5uZXdzJnV0bV9tZWRpdW09cmVmZXJyYWwmdXRtX2NhbXBhaWduPWJsb2NrY2hhaW4tY2FzaW5vcy1qdXN0LWhpdC1qYWNrcG90IiwicG9zdF9pZCI6IjE0NzZkYzc2LTRiNTgtNGNjMi05MjlhLTNjMGM1MTBiNjI3OSIsInB1YmxpY2F0aW9uX2lkIjoiYjMwZTUxN2UtZWM2MS00YzUwLWExZDYtYmRlNzA5YTFjMjUyIiwidmlzaXRfdG9rZW4iOiI4MmVjM2EzZS03YTBlLTQ5MzYtOWIyNy1mNGEwYjZlNzJiYzIiLCJpYXQiOjE2OTIxNTEwMjcuMzQ4LCJpc3MiOiJvcmNoaWQifQ.bGwebGkKY0gKqVu-3nYVONEBb6w0K9m7hKPSZ6XFnnY" target="_blank" rel="noopener noreferrer nofollow" style="color:#2346ea;text-decoration:underline #2346ea;"><b>top gainer</b></a></span></p></li><li style="margin:9px 0px 0px 0px;"><p style="text-align:left;"><span style="">+132.6% past week</span></p></li><li style="margin:9px 0px 0px 0px;"><p style="text-align:left;"><span style="">Fully on-chain casino</span></p></li><li style="margin:9px 0px 0px 0px;"><p style="text-align:left;"><span style="">Anyone can create their own service using WINR protocol</span></p></li><li style="margin:9px 0px 0px 0px;"><p style="text-align:left;"><span style="">Revenue sharing for $WINR token stakers</span></p></li></ul></div><style>
  p span[style*="font-size"] { line-height: 1.6; }
</style><div style="padding-bottom:18px;padding-left:0px;padding-right:0px;padding-top:6px;"><p style="color:#222222;color:var(--wt-text-on-background-color) !important;font-family:'Helvetica',Arial,sans-serif;font-size:17px;line-height:26px;text-align:left;"><span style=""><b>However,</b></span><span style=""> its one and only casino platform JustBet, doesn't quite offer as many features, and doesn’t have a user experience quite as slick, as Rollbit. </span></p></div><style>
  p span[style*="font-size"] { line-height: 1.6; }
</style><div style="padding-bottom:18px;padding-left:0px;padding-right:0px;padding-top:6px;"><p style="color:#222222;color:var(--wt-text-on-background-color) !important;font-family:'Helvetica',Arial,sans-serif;font-size:17px;line-height:26px;text-align:left;"><span style=""><b>—</b></span></p></div><style>
  p span[style*="font-size"] { line-height: 1.6; }
</style><div style="padding-bottom:18px;padding-left:0px;padding-right:0px;padding-top:6px;"><p style="color:#222222;color:var(--wt-text-on-background-color) !important;font-family:'Helvetica',Arial,sans-serif;font-size:17px;line-height:26px;text-align:left;"><span style="">Beyond these leaders, these projects on the horizon are also worth your attention:</span></p></div><style>
  p span[style*="font-size"] { line-height: 1.6; }
</style><div style="padding-bottom:18px;padding-left:0px;padding-right:0px;padding-top:6px;"><p style="color:#222222;color:var(--wt-text-on-background-color) !important;font-family:'Helvetica',Arial,sans-serif;font-size:17px;line-height:26px;text-align:left;"><span style=""><b>1/ </b></span><span style=""><a class="link" href="https://flight.beehiiv.net/v2/clicks/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1cmwiOiJodHRwczovL3BsYXkuemthc2luby5pby8_dXRtX3NvdXJjZT13d3cuY3J5cGRvbnV0cy5uZXdzJnV0bV9tZWRpdW09cmVmZXJyYWwmdXRtX2NhbXBhaWduPWJsb2NrY2hhaW4tY2FzaW5vcy1qdXN0LWhpdC1qYWNrcG90IiwicG9zdF9pZCI6IjE0NzZkYzc2LTRiNTgtNGNjMi05MjlhLTNjMGM1MTBiNjI3OSIsInB1YmxpY2F0aW9uX2lkIjoiYjMwZTUxN2UtZWM2MS00YzUwLWExZDYtYmRlNzA5YTFjMjUyIiwidmlzaXRfdG9rZW4iOiI4MmVjM2EzZS03YTBlLTQ5MzYtOWIyNy1mNGEwYjZlNzJiYzIiLCJpYXQiOjE2OTIxNTEwMjcuMzQ4LCJpc3MiOiJvcmNoaWQifQ.Mz7Q8WefEQgWeEJ2JJdYl8gZOFJhR-rMXRW2nyC6zsA" target="_blank" rel="noopener noreferrer nofollow" style="color:#2346ea;text-decoration:underline #2346ea;"><b>Zkasino</b></a></span></p></div><style>
  p span[style*="font-size"] { line-height: 1.6; }
</style><div style="padding-bottom:18px;padding-left:0px;padding-right:0px;padding-top:6px;"><p style="color:#222222;color:var(--wt-text-on-background-color) !important;font-family:'Helvetica',Arial,sans-serif;font-size:17px;line-height:26px;text-align:left;"><span style="">A fully on-chain casino platform with no utility token but a whopping total wagered of $283 million in just six months. </span></p></div><style>
  p span[style*="font-size"] { line-height: 1.6; }
</style><div style="padding-bottom:18px;padding-left:0px;padding-right:0px;padding-top:6px;"><p style="color:#222222;color:var(--wt-text-on-background-color) !important;font-family:'Helvetica',Arial,sans-serif;font-size:17px;line-height:26px;text-align:left;"><span style="">Their key roadmap has something called </span><span style=""><a class="link" href="https://flight.beehiiv.net/v2/clicks/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1cmwiOiJodHRwczovL2RvY3Muemthc2luby5pby96a2FzaW5vL3JvYWRtYXAtYW5kLWZhcT91dG1fc291cmNlPXd3dy5jcnlwZG9udXRzLm5ld3MmdXRtX21lZGl1bT1yZWZlcnJhbCZ1dG1fY2FtcGFpZ249YmxvY2tjaGFpbi1jYXNpbm9zLWp1c3QtaGl0LWphY2twb3QjYmFua3JvbGwtcG9vbHMiLCJwb3N0X2lkIjoiMTQ3NmRjNzYtNGI1OC00Y2MyLTkyOWEtM2MwYzUxMGI2Mjc5IiwicHVibGljYXRpb25faWQiOiJiMzBlNTE3ZS1lYzYxLTRjNTAtYTFkNi1iZGU3MDlhMWMyNTIiLCJ2aXNpdF90b2tlbiI6IjgyZWMzYTNlLTdhMGUtNDkzNi05YjI3LWY0YTBiNmU3MmJjMiIsImlhdCI6MTY5MjE1MTAyNy4zNDgsImlzcyI6Im9yY2hpZCJ9.EIvc4QnpLFVbGfzB07RIXNl4xi-SUbeOMhSaI6eiRc0" target="_blank" rel="noopener noreferrer nofollow" style="color:#2346ea;text-decoration:underline #2346ea;">Bankroll Pools</a></span><span style="">, where anyone will be able to provide liquidity to available bankrolls, and those liquidity providers will receive a share of revenue. Sounds fancy, right? It's worth a look if you're into investing in online casino house itself.</span></p></div><style>
  p span[style*="font-size"] { line-height: 1.6; }
</style><div style="padding-bottom:18px;padding-left:0px;padding-right:0px;padding-top:6px;"><p style="color:#222222;color:var(--wt-text-on-background-color) !important;font-family:'Helvetica',Arial,sans-serif;font-size:17px;line-height:26px;text-align:left;"><span style=""><b>2/ </b></span><span style=""><a class="link" href="https://flight.beehiiv.net/v2/clicks/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1cmwiOiJodHRwczovL2ZhcmVwcm90b2NvbC5pby8_dXRtX3NvdXJjZT13d3cuY3J5cGRvbnV0cy5uZXdzJnV0bV9tZWRpdW09cmVmZXJyYWwmdXRtX2NhbXBhaWduPWJsb2NrY2hhaW4tY2FzaW5vcy1qdXN0LWhpdC1qYWNrcG90IiwicG9zdF9pZCI6IjE0NzZkYzc2LTRiNTgtNGNjMi05MjlhLTNjMGM1MTBiNjI3OSIsInB1YmxpY2F0aW9uX2lkIjoiYjMwZTUxN2UtZWM2MS00YzUwLWExZDYtYmRlNzA5YTFjMjUyIiwidmlzaXRfdG9rZW4iOiI4MmVjM2EzZS03YTBlLTQ5MzYtOWIyNy1mNGEwYjZlNzJiYzIiLCJpYXQiOjE2OTIxNTEwMjcuMzQ4LCJpc3MiOiJvcmNoaWQifQ.qf1CRXD-ooyWaFc-bpNwzMBr9qJ2LatC1O-ddYu9b30" target="_blank" rel="noopener noreferrer nofollow" style="color:#2346ea;text-decoration:underline #2346ea;"><b>Fareplay</b></a></span></p></div><style>
  p span[style*="font-size"] { line-height: 1.6; }
</style><div style="padding-bottom:18px;padding-left:0px;padding-right:0px;padding-top:6px;"><p style="color:#222222;color:var(--wt-text-on-background-color) !important;font-family:'Helvetica',Arial,sans-serif;font-size:17px;line-height:26px;text-align:left;"><span style="">In Fareplay, you can only bet their own $FARE token. If you win, the protocol will mint new tokens to pay you out. If you lose, they burn the tokens you placed as bets. </span></p></div><style>
  p span[style*="font-size"] { line-height: 1.6; }
</style><div style="padding-bottom:18px;padding-left:0px;padding-right:0px;padding-top:6px;"><p style="color:#222222;color:var(--wt-text-on-background-color) !important;font-family:'Helvetica',Arial,sans-serif;font-size:17px;line-height:26px;text-align:left;"><span style="">And with the house having a slight advantage, the more the platform is used, the fewer $FARE tokens in circulation. A built-in deflationary mechanism at play!</span></p></div></div>
"""
output_text = input_text.replace("'", '"')
output_text = output_text.replace("\n",' ')

print(output_text)

# save as .sql
with open('data.sql', 'w') as f:
    f.write(output_text)