input_text = """
<div style="background-color:#ffffff;border-color:#eee;border-radius:15px;border-style:solid;border-width:1px;margin:0px 0px 0px 0px;padding:17px 17px 17px 17px;">
<style>
  p span[style*="font-size"] { line-height: 1.6; }
</style><div style="padding-bottom:16px;padding-left:0px;padding-right:0px;padding-top:6px;"><p style="color:#222222;color:var(--wt-text-on-background-color) !important;font-family:'Helvetica',Arial,sans-serif;font-size:17px;line-height:26px;text-align:left;"><span style="">Moons (MOON), the native token of the r/CryptoCurrency subreddit which boasts a community of over 6.5 million users, has increased by 400% following Reddit’s change in terms of service. </span></p></div><div style="padding-bottom:0px;padding-left:0px;padding-right:0px;padding-top:18px;"><h3 style="color:#000000;color:var(--wt-text-on-background-color) !important;font-family:'Helvetica',Arial,sans-serif;font-size:22px;font-weight:Bold;line-height:26px;margin:0;text-align:left;"><span style="">Reddit has its own cryptocurrency?</span></h3></div><style>
  p span[style*="font-size"] { line-height: 1.6; }
</style><div style="padding-bottom:16px;padding-left:0px;padding-right:0px;padding-top:6px;"><p style="color:#222222;color:var(--wt-text-on-background-color) !important;font-family:'Helvetica',Arial,sans-serif;font-size:17px;line-height:26px;text-align:left;"><span style="">Reddit introduced Community Points (</span><span style=""><a class="link" href="https://flight.beehiiv.net/v2/clicks/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1cmwiOiJodHRwczovL3d3dy5pbnZlc3RvcGVkaWEuY29tL25ld3Mvd2hhdC1lcmMyMC1hbmQtd2hhdC1kb2VzLWl0LW1lYW4tZXRoZXJldW0vP3V0bV9zb3VyY2U9d3d3LmNyeXBkb251dHMubmV3cyZ1dG1fbWVkaXVtPXJlZmVycmFsJnV0bV9jYW1wYWlnbj10by10aGUtbW9vbiIsInBvc3RfaWQiOiIyODdiYTM4Zi1hNWVkLTQyMjctOTFkMS0zOTA4MTE0ZWU3Y2EiLCJwdWJsaWNhdGlvbl9pZCI6ImIzMGU1MTdlLWVjNjEtNGM1MC1hMWQ2LWJkZTcwOWExYzI1MiIsInZpc2l0X3Rva2VuIjoiMmRiZWIwYjgtOTJkZC00ZWU5LWI0ODEtZDgzZTUzMWY1NTVkIiwiaWF0IjoxNjkyNTk3NTQzLjM1OSwiaXNzIjoib3JjaGlkIn0.rt1FS0VADHaDb1wglCRm2ybLUfVp-x_uNX53IToMdWw" target="_blank" rel="noopener noreferrer nofollow" style="-webkit-text-decoration:underline #2346ea;color:#2346ea;text-decoration:underline #2346ea;">ERC-20 tokens</a></span><span style="">) back in 2018 as an experiment, to boost user engagement in certain subreddits. After a successful test run, the r/CryptoCurrency community introduced MOON, and the r/Fortnite community, BRICK.</span></p></div><style>
  p span[style*="font-size"] { line-height: 1.6; }
</style><div style="padding-bottom:16px;padding-left:0px;padding-right:0px;padding-top:6px;"><p style="color:#222222;color:var(--wt-text-on-background-color) !important;font-family:'Helvetica',Arial,sans-serif;font-size:17px;line-height:26px;text-align:left;"><span style="">The Redditors can earn these points by posting, commenting, or anything to be active in the community. They can then spend these points to unlock special features or exclusive content.</span></p></div><div style="padding-bottom:0px;padding-left:0px;padding-right:0px;padding-top:18px;"><h3 style="color:#000000;color:var(--wt-text-on-background-color) !important;font-family:'Helvetica',Arial,sans-serif;font-size:22px;font-weight:Bold;line-height:26px;margin:0;text-align:left;"><span style="">Why the sudden surge?</span></h3></div><style>
  p span[style*="font-size"] { line-height: 1.6; }
</style><div style="padding-bottom:16px;padding-left:0px;padding-right:0px;padding-top:6px;"><p style="color:#222222;color:var(--wt-text-on-background-color) !important;font-family:'Helvetica',Arial,sans-serif;font-size:17px;line-height:26px;text-align:left;"><span style="">The two coins both skyrocketed following a Reddit post about Reddit’s updated terms of service, which permitted the trading of Verified Virtual Goods, which include avatars and the Community Points. Although this doesn’t set anything in stone, the community and Crypto.com got </span><span style=""><a class="link" href="https://flight.beehiiv.net/v2/clicks/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1cmwiOiJodHRwczovL3d3dy5jcnlwdG90aW1lcy5pby9jcnlwdG8tY29tLWxpc3RzLXJlZGRpdHMtbW9vbnMtdG9rZW4tb24tZXhjaGFuZ2UvP3V0bV9zb3VyY2U9d3d3LmNyeXBkb251dHMubmV3cyZ1dG1fbWVkaXVtPXJlZmVycmFsJnV0bV9jYW1wYWlnbj10by10aGUtbW9vbiIsInBvc3RfaWQiOiIyODdiYTM4Zi1hNWVkLTQyMjctOTFkMS0zOTA4MTE0ZWU3Y2EiLCJwdWJsaWNhdGlvbl9pZCI6ImIzMGU1MTdlLWVjNjEtNGM1MC1hMWQ2LWJkZTcwOWExYzI1MiIsInZpc2l0X3Rva2VuIjoiMmRiZWIwYjgtOTJkZC00ZWU5LWI0ODEtZDgzZTUzMWY1NTVkIiwiaWF0IjoxNjkyNTk3NTQzLjM1OSwiaXNzIjoib3JjaGlkIn0.DI5cCiIDXqkkrcj-oWdXiFaf1lLw6wgFOUUpN7JHOOc" target="_blank" rel="noopener noreferrer nofollow" style="-webkit-text-decoration:underline #2346ea;color:#2346ea;text-decoration:underline #2346ea;">super excited</a></span><span style="">.</span></p></div><style>
  p span[style*="font-size"] { line-height: 1.6; }
</style><div style="padding-bottom:16px;padding-left:0px;padding-right:0px;padding-top:6px;"><p style="color:#222222;color:var(--wt-text-on-background-color) !important;font-family:'Helvetica',Arial,sans-serif;font-size:17px;line-height:26px;text-align:left;"><span style="">Bobby Ong, the co-founder of CoinGecko </span><span style=""><a class="link" href="https://flight.beehiiv.net/v2/clicks/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1cmwiOiJodHRwczovL3R3aXR0ZXIuY29tL2JvYmJ5b25nL3N0YXR1cy8xNjgxMTM2NTk3Mzc3NjMwMjEwP3JlZl9zcmM9dHdzcmMlNUV0ZnclN0N0d2NhbXAlNUV0d2VldGVtYmVkJTdDdHd0ZXJtJTVFMTY4MTEzNjU5NzM3NzYzMDIxMCU3Q3R3Z3IlNUU3Y2U3MmQ0ZmY2MzViNDlhZDBmZWQ4ZDhiNjNlYjY1MTE3NzA0ZmI2JTdDdHdjb24lNUVzMV8mcmVmX3VybD1odHRwcyUzQSUyRiUyRnd3dy5hbHRjb2luYnV6ei5pbyUyRmJpdGNvaW4tYW5kLWNyeXB0by1ndWlkZSUyRnRoZXNlLXR3by1yZWRkaXQtY29pbnMtYXJlLWdldHRpbmctbWFzc2l2ZS1hZGRvcHRpb24lMkYiLCJwb3N0X2lkIjoiMjg3YmEzOGYtYTVlZC00MjI3LTkxZDEtMzkwODExNGVlN2NhIiwicHVibGljYXRpb25faWQiOiJiMzBlNTE3ZS1lYzYxLTRjNTAtYTFkNi1iZGU3MDlhMWMyNTIiLCJ2aXNpdF90b2tlbiI6IjJkYmViMGI4LTkyZGQtNGVlOS1iNDgxLWQ4M2U1MzFmNTU1ZCIsImlhdCI6MTY5MjU5NzU0My4zNTksImlzcyI6Im9yY2hpZCJ9.3nIkOixY4MpXT3Jxx73hLlq9yfIS8MFiLZGZuxxEeX0" target="_blank" rel="noopener noreferrer nofollow" style="-webkit-text-decoration:underline #2346ea;color:#2346ea;text-decoration:underline #2346ea;">commented</a></span><span style=""> that it was really inconvenient to trade Community Points but that this could change with Reddit supporting Community Points more actively.</span></p></div><div style="padding-bottom:0px;padding-left:0px;padding-right:0px;padding-top:18px;"><h3 style="color:#000000;color:var(--wt-text-on-background-color) !important;font-family:'Helvetica',Arial,sans-serif;font-size:22px;font-weight:Bold;line-height:26px;margin:0;text-align:left;"><span style="">Looking ahead</span></h3></div><style>
  p span[style*="font-size"] { line-height: 1.6; }
</style><div style="padding-bottom:16px;padding-left:0px;padding-right:0px;padding-top:6px;"><p style="color:#222222;color:var(--wt-text-on-background-color) !important;font-family:'Helvetica',Arial,sans-serif;font-size:17px;line-height:26px;text-align:left;"><span style="">Expect more subreddits to start issuing their own tokens, encouraging more users to actively participate in their communities. If you think it’s too late to get on MOON or BRICK now, it may be valid to wait for new subreddits’ Community Points to buy them early.</span></p></div></div>"""
output_text = input_text.replace('"', "'")
output_text = output_text.replace("\n",' ')

print(output_text)
