input_text = """
<div style="background-color:#ffffff;border-color:#eee;border-radius:15px;border-style:solid;border-width:1px;margin:0px 0px 0px 0px;padding:17px 17px 17px 17px;"><div style="padding-bottom:0px;padding-left:0px;padding-right:0px;padding-top:6px;"><h5 style="color:#ff4b6c;color:var(--wt-text-on-background-color) !important;font-family:'Helvetica',Arial,sans-serif;font-size:16px;font-weight:Bold;line-height:24px;margin:0;text-align:left;"><span style="">REGULATION</span></h5></div><div style="padding-bottom:5px;padding-left:0px;padding-right:0px;padding-top:5px;"><h1 style="color:#000000;color:var(--wt-text-on-background-color) !important;font-family:'Helvetica',Arial,sans-serif;font-size:27px;font-weight:Bold;line-height:41px;margin:0;text-align:left;"><span style="">Fed targets stablecoins day after PYUSD launch</span></h1></div><div style="padding-bottom:12px;padding-left:0px;padding-right:0px;padding-top:12px;"><img alt="" style="margin:0 auto 0 auto;width:100%;" src="https://media.beehiiv.com/cdn-cgi/image/fit=scale-down,format=auto,onerror=redirect,quality=80/uploads/asset/file/b797ed04-a863-49bb-9436-f21b72451943/image.png"></div><style>
  p span[style*="font-size"] { line-height: 1.6; }
</style><div style="padding-bottom:18px;padding-left:0px;padding-right:0px;padding-top:6px;"><p style="color:#222222;color:var(--wt-text-on-background-color) !important;font-family:'Helvetica',Arial,sans-serif;font-size:17px;line-height:26px;text-align:left;"><span style="">On Tuesday, the U.S. Federal Reserve (Fed) </span><span style=""><a class="link" href="https://flight.beehiiv.net/v2/clicks/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1cmwiOiJodHRwczovL3d3dy5yZXV0ZXJzLmNvbS90ZWNobm9sb2d5L3VzLWZlZC1jbGFyaWZpZXMtcHJvY2Vzcy1iYW5rcy10cmFuc2FjdC1zdGFibGVjb2lucy0yMDIzLTA4LTA4Lz91dG1fc291cmNlPXd3dy5jcnlwZG9udXRzLm5ld3MmdXRtX21lZGl1bT1yZWZlcnJhbCZ1dG1fY2FtcGFpZ249YmxvY2tjaGFpbi1jYXNpbm9zLWp1c3QtaGl0LWphY2twb3QiLCJwb3N0X2lkIjoiMTQ3NmRjNzYtNGI1OC00Y2MyLTkyOWEtM2MwYzUxMGI2Mjc5IiwicHVibGljYXRpb25faWQiOiJiMzBlNTE3ZS1lYzYxLTRjNTAtYTFkNi1iZGU3MDlhMWMyNTIiLCJ2aXNpdF90b2tlbiI6IjMzYTBjMWE4LWQxYjktNGJhOS05ODkwLTdmM2M2OGUwYmYyYiIsImlhdCI6MTY5MTcyMjM5Mi45NTksImlzcyI6Im9yY2hpZCJ9.0FUWM90c-w_yClTzWoZ4HUqXPC9pe0pbNqBHO6jjBXg" target="_blank" rel="noopener noreferrer nofollow" style="color:#2346ea;text-decoration:underline #2346ea;">announced</a></span><span style=""> enhanced regulations for cryptocurrency-related banking activities. This comes just a day after PayPal’s </span><span style=""><a class="link" href="https://flight.beehiiv.net/v2/clicks/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1cmwiOiJodHRwczovL3d3dy5jcnlwZG9udXRzLm5ld3MvcC9wYXlwYWwtcy1uZXctY3J5cHRvLWdhbWUtY2hhbmdlciIsInBvc3RfaWQiOiIxNDc2ZGM3Ni00YjU4LTRjYzItOTI5YS0zYzBjNTEwYjYyNzkiLCJwdWJsaWNhdGlvbl9pZCI6ImIzMGU1MTdlLWVjNjEtNGM1MC1hMWQ2LWJkZTcwOWExYzI1MiIsInZpc2l0X3Rva2VuIjoiMzNhMGMxYTgtZDFiOS00YmE5LTk4OTAtN2YzYzY4ZTBiZjJiIiwiaWF0IjoxNjkxNzIyMzkyLjk1OSwiaXNzIjoib3JjaGlkIn0.f1QAfYcv_7-1xR4z-KGYlwnWr71P21t5nLITLWbilBw" target="_blank" rel="noopener noreferrer nofollow" style="color:#2346ea;text-decoration:underline #2346ea;">announcement</a></span><span style=""> of their PYUSD stablecoins.</span></p></div><style>
  p span[style*="font-size"] { line-height: 1.6; }
</style><div style="padding-bottom:18px;padding-left:0px;padding-right:0px;padding-top:6px;"><p style="color:#222222;color:var(--wt-text-on-background-color) !important;font-family:'Helvetica',Arial,sans-serif;font-size:17px;line-height:26px;text-align:left;"><span style="">These below rules are meant to keep things steady in the banking world, as crypto-related businesses have the potential to shake up banks: </span></p></div><style>
  p span[style*="font-size"] { line-height: 1.6; }
</style><div style="padding-bottom:18px;padding-left:0px;padding-right:0px;padding-top:6px;"><p style="color:#222222;color:var(--wt-text-on-background-color) !important;font-family:'Helvetica',Arial,sans-serif;font-size:17px;line-height:26px;text-align:left;"><span style=""><b>1. Pre-approval needed for stablecoins:</b></span><span style=""> Banks looking to get into stablecoins must get a thumbs-up from the Fed first. They'll need to demonstrate that they can handle cyberscurity threats, liquidity issues, consumer protection, illegal financial activities, and a bunch of other risks.</span></p></div><style>
  p span[style*="font-size"] { line-height: 1.6; }
</style><div style="padding-bottom:18px;padding-left:0px;padding-right:0px;padding-top:6px;"><p style="color:#222222;color:var(--wt-text-on-background-color) !important;font-family:'Helvetica',Arial,sans-serif;font-size:17px;line-height:26px;text-align:left;"><span style=""><b>2. Bank collaboration with non-bank entities:</b></span><span style=""> Even if a bank partners with non-bank players to offer blockchain-based services, they'll still be under regulatory oversight.</span></p></div><style>
  p span[style*="font-size"] { line-height: 1.6; }
</style><div style="padding-bottom:18px;padding-left:0px;padding-right:0px;padding-top:6px;"><p style="color:#222222;color:var(--wt-text-on-background-color) !important;font-family:'Helvetica',Arial,sans-serif;font-size:17px;line-height:26px;text-align:left;"><span style="">Market vibes are mixed. People are wary, given how Facebook's Libra project belly-flopped due to regulatory issues. Congresswoman Maxine Waters is also </span><span style=""><a class="link" href="https://flight.beehiiv.net/v2/clicks/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1cmwiOiJodHRwczovL3d3dy5jb2luZGVzay5jb20vcG9saWN5LzIwMjMvMDgvMDkvY29uZ3Jlc3N3b21hbi1tYXhpbmUtd2F0ZXJzLXNheXMtc2hlcy1kZWVwbHktY29uY2VybmVkLWFib3V0LXBheXBhbHMtbmV3LXN0YWJsZWNvaW4vP3V0bV9zb3VyY2U9d3d3LmNyeXBkb251dHMubmV3cyZ1dG1fbWVkaXVtPXJlZmVycmFsJnV0bV9jYW1wYWlnbj1ibG9ja2NoYWluLWNhc2lub3MtanVzdC1oaXQtamFja3BvdCIsInBvc3RfaWQiOiIxNDc2ZGM3Ni00YjU4LTRjYzItOTI5YS0zYzBjNTEwYjYyNzkiLCJwdWJsaWNhdGlvbl9pZCI6ImIzMGU1MTdlLWVjNjEtNGM1MC1hMWQ2LWJkZTcwOWExYzI1MiIsInZpc2l0X3Rva2VuIjoiMzNhMGMxYTgtZDFiOS00YmE5LTk4OTAtN2YzYzY4ZTBiZjJiIiwiaWF0IjoxNjkxNzIyMzkyLjk2LCJpc3MiOiJvcmNoaWQifQ.ZkCtp-07-cF4eIlQPb9Vh5ofvVNap69ci08zAJhshG4" target="_blank" rel="noopener noreferrer nofollow" style="color:#2346ea;text-decoration:underline #2346ea;">throwing shade</a></span><span style=""> on PayPal's stablecoin project, hinting it might be stopped.</span></p></div><style>
  p span[style*="font-size"] { line-height: 1.6; }
</style><div style="padding-bottom:18px;padding-left:0px;padding-right:0px;padding-top:6px;"><p style="color:#222222;color:var(--wt-text-on-background-color) !important;font-family:'Helvetica',Arial,sans-serif;font-size:17px;line-height:26px;text-align:left;"><span style=""><b>Yet, it's not all gloomy.</b></span><span style=""> Patrick McHenry, the current chair of the House Financial Services Committee expressed support for PYUSD, and if PayPal rolls out PYUSD in line with the Fed's criteria, it could be the first stablecoin officially approved by the Fed. This could potentially help stabilize the price volatility that plagues stablecoins.</span></p></div></div>"""

output_text = input_text.replace('"', "'")
output_text = output_text.replace("\n", " ")

print(output_text)