version: '3.9'
services:
#  mysql:
#    image: mysql:latest
#    container_name: data
#    restart: always
#    environment:
#      MYSQL_ROOT_PASSWORD: 
#      MYSQL_DATABASE: donut
#      MYSQL_USER: root
#      MYSQL_PASSWORD: 
#    ports:
#      - "3306:3306"
#    volumes:
#      - mysql_data:/var/lib/mysql

  spring-app:
    image: back:latest
    container_name: back
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/db_name?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 

  react-app:
    image: front:latest
    container_name: react_app_container
    restart: always
    ports:
      - "3000:3000"
      -
volumes:
  mysql_data:
