version: '3'
services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: aimdyohan
      MYSQL_DATABASE: donut
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  spring-app:
    build:
      context:
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - mysql
volumes:
  mysql_data: